server:
  port: ${SERVER_PORT:8084}

spring:
  application:
    name: organization-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/organization_db}
    username: ${SPRING_DATASOURCE_USERNAME:org_user}
    password: ${SPRING_DATASOURCE_PASSWORD:org_pass}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH_ISSUER_URI:http://localhost:8085}

app:
  cors:
    enabled: false

axon:
  axonserver:
    servers: ${AXONIQ_AXONSERVER_SERVERS:localhost:8124}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  health:
    axon:
      enabled: true

